# Generated by Django 5.2.4 on 2025-08-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('empid', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
