# Generated by Django 5.2.4 on 2025-08-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contactusform',
        ),
    ]
